language: java

install: /bin/true

services:
  - postgresql

jdk:
  - oraclejdk8

before_install:
- gradle wrapper
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

before_script:
    - wget https://services.gradle.org/distributions/gradle-2.14-bin.zip
    - unzip gradle-2.14-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.14
    - export PATH=$GRADLE_HOME/bin:$PATH
    - psql -c 'CREATE TABLE "Repositories" (Id UUID, Name text, Url text, Stars integer, Description text, Language text, CommitsNum integer);' -U postgres maxmax
    - psql -c 'CREATE TABLE "Languages" (Id TEXT, Name TEXT);' -U postgres maxmax
    - psql -c 'CREATE TABLE "Users" (Id TEXT, Login TEXT, Url TEXT, Score INTEGER);' -U postgres maxmax
    - psql -c 'CREATE TABLE "Contributors" (Id TEXT, Login TEXT, contributions INTEGER);' -U postgres maxmax
    - psql -c 'CREATE TABLE "RepositoryOwners" (Id TEXT, Login TEXT, Url TEXT);' -U postgres maxmax

script:
- ./gradlew assemble
- ./gradlew check
- ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
